# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bid',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
